
# aws:
#   access_key_id: 123
#   secret_access_key: 345

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: 444444444444444444444444444444444444444444444444

aws:
  access_key_id: 'your access key'
  secret_access_key: 'you secret access key'
  region: 'aws region,e.g. us-east-1'

development:
  postgres_password: 'your postgres pwd'
  postgres_user: 'your postgres user'
  aws_s3_bucket: 'your s3 bucket for files and document upload'
  aws_s3_db_bucket: 'your s3 bucket for the database backup'
  gpg_email_address: 'your email address to keep the private key for encryption'

production:
  postgres_password: 'your postgres pwd'
  postgres_user: 'your postgres user'
  aws_s3_bucket: 'your s3 bucket for files and document upload'
  aws_s3_db_bucket: 'your s3 bucket for the database backup'
  gpg_email_address: 'your email address to keep the private key for encryption'
